# Generated by Django 6.0.1 on 2026-01-19 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], default='F', max_length=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('a_agenda', models.BooleanField(default=True)),
                ('heure_ouverture', models.TimeField(default='07:00')),
                ('heure_fermeture', models.TimeField(default='23:00')),
                ('fond_caisse', models.IntegerField(default=30000)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Institut',
                'verbose_name_plural': 'Instituts',
            },
        ),
        migrations.CreateModel(
            name='FamillePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(default='#e8b4b8', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles', to='core.institut')),
            ],
            options={
                'verbose_name': 'Famille de prestation',
                'verbose_name_plural': 'Familles de prestations',
                'ordering': ['institut', 'ordre_affichage', 'nom'],
                'unique_together': {('nom', 'institut')},
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='core.institut')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['institut', 'ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.IntegerField()),
                ('a_quantite', models.BooleanField(default=False)),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.institut')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ['institut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('duree', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prix', models.IntegerField()),
                ('unite', models.CharField(blank=True, max_length=50, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations', to='core.familleprestation')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['famille', 'ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('prix_base', models.IntegerField()),
                ('prix_options', models.IntegerField(default=0)),
                ('prix_total', models.IntegerField()),
                ('prix_modifie', models.BooleanField(default=False)),
                ('prix_original', models.IntegerField(blank=True, null=True)),
                ('raison_modification', models.CharField(blank=True, max_length=200, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('valide', 'Validé'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.client')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.employe')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.familleprestation')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='core.institut')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rendez_vous', to='core.prestation')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date', 'heure_debut', 'employe'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte')], max_length=20)),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.IntegerField()),
                ('montant_paye', models.IntegerField(default=0)),
                ('reste_a_payer', models.IntegerField()),
                ('solde', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_solde', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.client')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='core.institut')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Crédit',
                'verbose_name_plural': 'Crédits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RendezVousOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.option')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_selectionnees', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Option de rendez-vous',
                'verbose_name_plural': 'Options de rendez-vous',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('patron', 'Patron'), ('manager', 'Manager')], max_length=20)),
                ('pin', models.CharField(max_length=6)),
                ('actif', models.BooleanField(default=True)),
                ('institut', models.ForeignKey(blank=True, help_text='NULL pour le patron (accès à tous)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.institut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_crees', to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdv_valides', to='core.utilisateur'),
        ),
        migrations.CreateModel(
            name='PaiementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('mode', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.credit')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Paiement de crédit',
                'verbose_name_plural': 'Paiements de crédits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modification', models.CharField(choices=[('prix_rdv', 'Modification prix RDV'), ('ajout_prestation', 'Ajout prestation'), ('modif_prestation', 'Modification prestation'), ('ajout_option', 'Ajout option'), ('modif_option', 'Modification option')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('valeur_avant', models.CharField(blank=True, max_length=200, null=True)),
                ('valeur_apres', models.CharField(blank=True, max_length=200, null=True)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institut')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rendezvous')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Log de modification',
                'verbose_name_plural': 'Logs de modifications',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VenteExpressPrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.IntegerField()),
                ('prix_total', models.IntegerField()),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.prestation')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestations_express', to='core.rendezvous')),
            ],
        ),
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_especes_calcule', models.IntegerField(default=0)),
                ('total_carte_calcule', models.IntegerField(default=0)),
                ('total_calcule', models.IntegerField(default=0)),
                ('montant_reel_especes', models.IntegerField(blank=True, null=True)),
                ('fond_caisse', models.IntegerField(default=30000)),
                ('ecart', models.IntegerField(default=0)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('cloture', models.BooleanField(default=False)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='core.institut')),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Clôture de caisse',
                'verbose_name_plural': 'Clôtures de caisse',
                'ordering': ['-date'],
                'unique_together': {('institut', 'date')},
            },
        ),
    ]
