# Generated by Django 6.0.1 on 2026-01-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_email_to_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloturecaisse',
            options={'ordering': ['-date', '-date_cloture'], 'verbose_name': 'Clôture de caisse', 'verbose_name_plural': 'Clôtures de caisse'},
        ),
        migrations.AlterUniqueTogether(
            name='cloturecaisse',
            unique_together=set(),
        ),
    ]
