# Generated by Django 6.0.1 on 2026-01-27 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cloturecaisse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('carte_cadeau', 'Carte cadeau')], max_length=20),
        ),
        migrations.CreateModel(
            name='CarteCadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True)),
                ('montant_initial', models.IntegerField()),
                ('solde', models.IntegerField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('soldee', 'Soldée'), ('annulee', 'Annulée')], default='active', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_utilisation', models.DateTimeField(blank=True, null=True)),
                ('mode_paiement_achat', models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire')], default='especes', max_length=20)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartes_achetees', to='core.client')),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartes_recues', to='core.client')),
                ('institut_achat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartes_vendues', to='core.institut')),
                ('vendue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_vendues', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Carte cadeau',
                'verbose_name_plural': 'Cartes cadeaux',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationCarteCadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='core.cartecadeau')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_cartes', to='core.institut')),
                ('rendez_vous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_carte_cadeau', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Utilisation carte cadeau',
                'verbose_name_plural': 'Utilisations cartes cadeaux',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='utilisation_carte_cadeau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisationcartecadeau'),
        ),
    ]
