# Generated by Django 6.0.1 on 2026-01-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_paiement_mode_cartecadeau_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_cheque_calcule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_om_calcule',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cloturecaisse',
            name='total_wave_calcule',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartecadeau',
            name='mode_paiement_achat',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave')], default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave'), ('carte_cadeau', 'Carte cadeau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiementcredit',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave')], max_length=20),
        ),
    ]
