# Generated by Django 6.0.1 on 2026-01-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cloturecaisse_total_cheque_calcule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('valide', 'Validé'), ('annule', 'Annulé'), ('absent', 'Absent'), ('annule_client', 'Annulé par le client')], default='planifie', max_length=20),
        ),
    ]
