# Generated by Django 6.0.1 on 2026-01-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='est_forfait',
            field=models.BooleanField(default=False, help_text="True si c'est un forfait multi-séances"),
        ),
        migrations.AddField(
            model_name='prestation',
            name='nombre_seances',
            field=models.IntegerField(default=1, help_text='Nombre de séances incluses dans le forfait'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='est_seance_forfait',
            field=models.BooleanField(default=False, help_text='True si ce RDV est une séance de forfait'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='numero_seance',
            field=models.IntegerField(blank=True, help_text='Numéro de la séance dans le forfait (ex: 3 sur 6)', null=True),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave'), ('carte_cadeau', 'Carte cadeau'), ('forfait', 'Forfait')], max_length=20),
        ),
        migrations.CreateModel(
            name='ForfaitClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seances_total', models.IntegerField(help_text='Nombre total de séances du forfait')),
                ('nombre_seances_utilisees', models.IntegerField(default=0, help_text='Nombre de séances déjà effectuées')),
                ('nombre_seances_programmees', models.IntegerField(default=0, help_text='Nombre de séances avec RDV planifié')),
                ('prix_total', models.IntegerField(help_text='Prix total du forfait')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='actif', max_length=20)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_seance', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date de fin quand toutes les séances sont utilisées', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forfaits', to='core.client')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forfaits_vendus', to='core.institut')),
                ('prestation', models.ForeignKey(limit_choices_to={'est_forfait': True}, on_delete=django.db.models.deletion.PROTECT, related_name='forfaits_vendus', to='core.prestation')),
                ('vendu_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forfaits_vendus', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Forfait client',
                'verbose_name_plural': 'Forfaits clients',
                'ordering': ['-date_achat'],
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='forfait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='core.forfaitclient'),
        ),
        migrations.CreateModel(
            name='SeanceForfait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numéro de la séance (1, 2, 3...)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('programmee', 'Programmée'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='disponible', max_length=20)),
                ('date_programmation', models.DateTimeField(blank=True, null=True)),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('forfait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='core.forfaitclient')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance_forfait', to='core.rendezvous')),
            ],
            options={
                'verbose_name': 'Séance de forfait',
                'verbose_name_plural': 'Séances de forfait',
                'ordering': ['forfait', 'numero'],
                'unique_together': {('forfait', 'numero')},
            },
        ),
    ]
