# Generated by Django 6.0.1 on 2026-01-31 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_forfaits_multi_seances'),
    ]

    operations = [
        migrations.AddField(
            model_name='familleprestation',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='familleprestation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='familleprestation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prestation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='duree_minutes',
            field=models.IntegerField(blank=True, help_text='Durée en minutes (peut être vide pour les options)', null=True),
        ),
        migrations.AddField(
            model_name='prestation',
            name='instituts',
            field=models.ManyToManyField(blank=True, help_text='Instituts où cette prestation est disponible', related_name='prestations_disponibles', to='core.institut'),
        ),
        migrations.AddField(
            model_name='prestation',
            name='type_prestation',
            field=models.CharField(choices=[('normal', 'Normal'), ('option', 'Option'), ('forfait', 'Forfait')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='familleprestation',
            name='couleur',
            field=models.CharField(default='#e8b4b8', help_text="Couleur hexadécimale pour l'affichage dans l'agenda", max_length=7),
        ),
        migrations.AlterField(
            model_name='familleprestation',
            name='ordre_affichage',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage dans le catalogue"),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='duree',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Durée en heures (ancien format, sera migré vers duree_minutes)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='nombre_seances',
            field=models.IntegerField(default=1, help_text='Nombre de séances (pour les forfaits)'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='ordre_affichage',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage dans la famille"),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix',
            field=models.IntegerField(help_text='Prix en CFA'),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='unite',
            field=models.CharField(blank=True, help_text="Unité pour les options (ex: 'par strass', 'par ongle', 'par mèche')", max_length=50, null=True),
        ),
    ]
