# Generated by Django 6.0.1 on 2026-02-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_familleprestation_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecadeau',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text="Date d'expiration (6 mois après l'achat)", null=True),
        ),
        migrations.AlterField(
            model_name='cartecadeau',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('soldee', 'Soldée'), ('annulee', 'Annulée'), ('supprimee', 'Supprimée')], default='active', max_length=20),
        ),
    ]
