# Generated by Django 6.0.1 on 2026-02-06 07:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cartecadeau_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementcredit',
            name='utilisation_carte_cadeau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_credit', to='core.utilisationcartecadeau'),
        ),
        migrations.AlterField(
            model_name='cartecadeau',
            name='montant_initial',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cartecadeau',
            name='solde',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='fond_caisse',
            field=models.IntegerField(default=30000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='montant_reel_especes',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_carte_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_cheque_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_especes_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_om_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cloturecaisse',
            name='total_wave_calcule',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='montant_paye',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='montant_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reste_a_payer',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forfaitclient',
            name='nombre_seances_programmees',
            field=models.IntegerField(default=0, help_text='Nombre de séances avec RDV planifié', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forfaitclient',
            name='nombre_seances_total',
            field=models.IntegerField(help_text='Nombre total de séances du forfait', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='forfaitclient',
            name='nombre_seances_utilisees',
            field=models.IntegerField(default=0, help_text='Nombre de séances déjà effectuées', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='forfaitclient',
            name='prix_total',
            field=models.IntegerField(help_text='Prix total du forfait', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave'), ('carte_cadeau', 'Carte cadeau'), ('forfait', 'Forfait'), ('offert', 'Offert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paiementcredit',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave'), ('carte_cadeau', 'Carte cadeau')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paiementcredit',
            name='montant',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix',
            field=models.IntegerField(help_text='Prix en CFA', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prix_base',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prix_options',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prix_original',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prix_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvousoption',
            name='prix_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvousoption',
            name='prix_unitaire',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rendezvousoption',
            name='quantite',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='seanceforfait',
            name='numero',
            field=models.IntegerField(help_text='Numéro de la séance (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='utilisationcartecadeau',
            name='montant',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venteexpressprestation',
            name='prix_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venteexpressprestation',
            name='prix_unitaire',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venteexpressprestation',
            name='quantite',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
