# Generated by Django 6.0.2 on 2026-02-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_carte_cadeau_to_paiement_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
