# Generated by Django 6.0.2 on 2026-02-08 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_client_ajout_champ_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfaitclient',
            name='montant_paye_initial',
            field=models.IntegerField(default=0, help_text="Montant payé à l'achat du forfait", validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
