# Generated by Django 6.0.2 on 2026-02-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_forfait_montant_paye_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartecadeau',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('soldee', 'Soldée'), ('annulee', 'Annulée'), ('supprimee', 'Supprimée')], default='active', max_length=20),
        ),
    ]
