# Generated by Django 6.0.2 on 2026-02-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carte_cadeau_statut_expiree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='pin',
            field=models.CharField(max_length=256),
        ),
    ]
