# Generated by Django 6.0.2 on 2026-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pin_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecadeau',
            name='montant_paiement_1',
            field=models.IntegerField(blank=True, help_text='Montant payé avec le 1er moyen (= montant_initial si paiement simple)', null=True),
        ),
        migrations.AddField(
            model_name='cartecadeau',
            name='montant_paiement_2',
            field=models.IntegerField(blank=True, help_text='Montant payé avec le 2ème moyen', null=True),
        ),
        migrations.AddField(
            model_name='cartecadeau',
            name='moyen_paiement_2',
            field=models.CharField(blank=True, choices=[('especes', 'Espèces'), ('carte', 'Carte bancaire'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave')], max_length=20, null=True),
        ),
    ]
