# Generated by Django 6.0.2 on 2026-02-19 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_carte_cadeau_double_paiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeRDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('nombre_rdv', models.IntegerField(default=1)),
                ('prix_total', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_rdv', to='core.client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes_rdv_crees', to='core.utilisateur')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_rdv', to='core.institut')),
            ],
            options={
                'verbose_name': 'Groupe de RDV',
                'verbose_name_plural': 'Groupes de RDV',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='groupe',
            field=models.ForeignKey(blank=True, help_text="Groupe auquel appartient ce RDV (si créé avec d'autres)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous', to='core.grouperdv'),
        ),
    ]
