# Generated by Django 6.0.2 on 2026-02-23 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_grouperdv_rendezvous_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouperdv',
            name='duree_personnalisee',
            field=models.IntegerField(blank=True, help_text='Durée totale personnalisée en minutes (remplace la somme des durées des prestations)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
