# Generated by Django 6.0.2 on 2026-02-26 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rendezvous_rappel_envoye'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('couleur', models.CharField(default='#3498db', max_length=7)),
                ('ordre_affichage', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Catégorie d'employé",
                'verbose_name_plural': "Catégories d'employés",
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['ordre_affichage', 'nom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AddField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='est_dans_agenda',
            field=models.BooleanField(default=True, help_text='False pour vigiles, ménage, etc.'),
        ),
        migrations.AddField(
            model_name='employe',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='rang',
            field=models.CharField(choices=[('superieur', 'Supérieur'), ('manager', 'Manager'), ('employe', 'Employé')], default='employe', max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='salaire_base',
            field=models.IntegerField(default=0, help_text='Salaire mensuel de base en CFA', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='employe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='institut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='core.institut'),
        ),
        migrations.AddField(
            model_name='employe',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='core.categorieemploye'),
        ),
    ]
