# Generated by Django 6.0.2 on 2026-02-26 13:21

from django.db import migrations


def creer_categories_defaut(apps, schema_editor):
    """Crée les catégories d'employés par défaut."""
    CategorieEmploye = apps.get_model('core', 'CategorieEmploye')
    categories = [
        ('Manager', '#9b59b6', 1),
        ('Esthéticienne senior', '#3498db', 2),
        ('Esthéticienne junior', '#27ae60', 3),
        ('Stagiaire', '#f39c12', 4),
        ('Prothésiste ongulaire', '#e74c3c', 5),
        ('Vigile', '#95a5a6', 6),
        ('Fille de ménage', '#7f8c8d', 7),
    ]
    for nom, couleur, ordre in categories:
        CategorieEmploye.objects.get_or_create(
            nom=nom,
            defaults={'couleur': couleur, 'ordre_affichage': ordre}
        )


def supprimer_categories_defaut(apps, schema_editor):
    """Rollback : supprime les catégories créées."""
    CategorieEmploye = apps.get_model('core', 'CategorieEmploye')
    noms = [
        'Manager', 'Esthéticienne senior', 'Esthéticienne junior',
        'Stagiaire', 'Prothésiste ongulaire', 'Vigile', 'Fille de ménage',
    ]
    CategorieEmploye.objects.filter(nom__in=noms).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_categorieemploye_and_update_employe'),
    ]

    operations = [
        migrations.RunPython(creer_categories_defaut, supprimer_categories_defaut),
    ]
