# Generated by Django 6.0.2 on 2026-02-26 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_insert_categories_employe_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Type d'absence",
                'verbose_name_plural': "Types d'absence",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Avertissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avertissement', models.CharField(choices=[('retard', 'Retards répétés'), ('absence', 'Absences répétées'), ('autre', 'Autre')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('mois_concerne', models.DateField()),
                ('nombre_retards', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('mise_a_pied', models.BooleanField(default=False)),
                ('jours_mise_a_pied', models.IntegerField(default=0)),
                ('date_debut_mise_a_pied', models.DateField(blank=True, null=True)),
                ('date_fin_mise_a_pied', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avertissements', to='core.employe')),
            ],
            options={
                'verbose_name': 'Avertissement',
                'verbose_name_plural': 'Avertissements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('justificatif_recu', models.BooleanField(default=False)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_creees', to='core.utilisateur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='core.employe')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_validees', to='core.utilisateur')),
                ('type_absence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeabsence')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut_arrivee', models.CharField(choices=[('present', 'Présent'), ('retard', 'Retard'), ('absent', 'Absent')], default='present', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('statut_depart', models.CharField(blank=True, choices=[('present', 'Présent'), ('retard', 'Retard'), ('absent', 'Absent')], max_length=20, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='core.employe')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', 'employe'],
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
