# Generated by Django 6.0.2 on 2026-02-26 16:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_insert_types_absence_defaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de prime',
                'verbose_name_plural': 'Types de prime',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Avance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('montant', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_mois_remboursement', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_mensuel', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('montant_rembourse', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('rembourse', 'Remboursé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='core.employe')),
            ],
            options={
                'verbose_name': 'Avance',
                'verbose_name_plural': 'Avances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Prime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('montant', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primes', to='core.employe')),
                ('type_prime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.typeprime')),
            ],
            options={
                'verbose_name': 'Prime',
                'verbose_name_plural': 'Primes',
                'ordering': ['-mois', 'employe'],
            },
        ),
        migrations.CreateModel(
            name='CalculSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('salaire_base', models.IntegerField(default=0)),
                ('jours_travailles', models.IntegerField(default=0)),
                ('jours_absence_non_payee', models.IntegerField(default=0)),
                ('montant_retenue_absences', models.IntegerField(default=0)),
                ('total_primes', models.IntegerField(default=0)),
                ('total_avances_deduites', models.IntegerField(default=0)),
                ('net_a_payer', models.IntegerField(default=0)),
                ('details_primes', models.JSONField(blank=True, default=list)),
                ('details_absences', models.JSONField(blank=True, default=list)),
                ('details_avances', models.JSONField(blank=True, default=list)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('paye', 'Payé')], default='brouillon', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='core.employe')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaires_valides', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Calcul de salaire',
                'verbose_name_plural': 'Calculs de salaires',
                'ordering': ['-mois', 'employe'],
                'unique_together': {('employe', 'mois')},
            },
        ),
    ]
