# Generated by Django 6.0.2 on 2026-02-27 10:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_depense_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.IntegerField(default=0)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('om', 'Orange Money'), ('carte', 'Carte bancaire')], max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_produits', to='core.client')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_produits', to='core.institut')),
            ],
            options={
                'verbose_name': 'Vente produit',
                'verbose_name_plural': 'Ventes produits',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneVenteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sous_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.venteproduit')),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('recettes_rdv', models.IntegerField(default=0)),
                ('recettes_ventes', models.IntegerField(default=0)),
                ('recettes_attendues', models.IntegerField(default=0)),
                ('caisse_especes', models.IntegerField(default=0)),
                ('caisse_wave', models.IntegerField(default=0)),
                ('caisse_om', models.IntegerField(default=0)),
                ('caisse_carte', models.IntegerField(default=0)),
                ('caisse_reelle', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('commentaire_ecart', models.TextField(blank=True, null=True)),
                ('valide', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('institut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.institut')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Réconciliation caisse',
                'verbose_name_plural': 'Réconciliations caisse',
                'ordering': ['-date'],
                'unique_together': {('date', 'institut')},
            },
        ),
    ]
