# Generated by Django 6.0.2 on 2026-02-27 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_ventes_reconciliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.IntegerField(default=0, help_text='0 si non vendu aux clients', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
