# Generated by Django 6.0.2 on 2026-02-27 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_prix_vente_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('montant', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('beneficiaire', models.CharField(blank=True, default='', max_length=200)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('carte', 'Carte bancaire'), ('om', 'Orange Money'), ('wave', 'Wave'), ('autre', 'Autre')], default='especes', max_length=20)),
                ('frequence', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=20)),
                ('jour_du_mois', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrentes', to='core.categoridepense')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
                ('institut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_recurrentes', to='core.institut')),
            ],
            options={
                'verbose_name': 'Dépense récurrente',
                'verbose_name_plural': 'Dépenses récurrentes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField(default=0)),
                ('quantite_reelle', models.IntegerField(default=0)),
                ('ecart', models.IntegerField(default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.inventaire')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
            options={
                'ordering': ['produit__categorie__nom', 'produit__nom'],
                'unique_together': {('inventaire', 'produit')},
            },
        ),
        migrations.CreateModel(
            name='ValidationDepenseRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('ignore', 'Ignoré')], default='en_attente', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.depense')),
                ('depense_recurrente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.depenserecurrente')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Validation dépense récurrente',
                'ordering': ['-mois'],
                'unique_together': {('depense_recurrente', 'mois')},
            },
        ),
    ]
