# Generated by Django 6.0.2 on 2026-03-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_categoriedepense_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculsalaire',
            name='deduction_absences_pointage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calculsalaire',
            name='nb_absences_non_justifiees',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='calculsalaire',
            name='nb_retards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_depart_midi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='heure_retour_midi',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presence',
            name='minutes_retard',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presence',
            name='statut_journee',
            field=models.CharField(choices=[('present', 'Présent'), ('absent_justifie', 'Absent justifié'), ('absent_non_justifie', 'Absent non justifié'), ('conge_long', 'Congé / arrêt long terme'), ('demi_journee_matin', 'Demi-journée matin'), ('demi_journee_apmidi', 'Demi-journée après-midi')], default='present', max_length=30),
        ),
        migrations.AddField(
            model_name='presence',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_presence', to='core.employe'),
        ),
        migrations.AlterField(
            model_name='depenserecurrente',
            name='frequence',
            field=models.CharField(choices=[('mensuel', 'Mensuel (chaque mois)'), ('bimestriel', 'Tous les 2 mois'), ('trimestriel', 'Trimestriel (tous les 3 mois)'), ('semestriel', 'Semestriel (tous les 6 mois)'), ('annuel', 'Annuel')], default='mensuel', max_length=20),
        ),
        migrations.AlterField(
            model_name='venteproduit',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('wave', 'Wave'), ('om', 'Orange Money'), ('carte', 'Carte bancaire'), ('carte_cadeau', 'Carte cadeau')], max_length=20),
        ),
        migrations.CreateModel(
            name='HoraireEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(default='08:00')),
                ('heure_fin', models.TimeField(default='17:00')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='core.employe')),
            ],
            options={
                'verbose_name': 'Horaire employé',
                'verbose_name_plural': 'Horaires employés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ModificationPointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('champ_modifie', models.CharField(max_length=50)),
                ('ancienne_valeur', models.CharField(blank=True, max_length=50)),
                ('nouvelle_valeur', models.CharField(blank=True, max_length=50)),
                ('motif', models.TextField(blank=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_pointage', to='core.utilisateur')),
                ('presence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='core.presence')),
            ],
            options={
                'verbose_name': 'Modification de pointage',
                'verbose_name_plural': 'Modifications de pointage',
                'ordering': ['-date_modification'],
            },
        ),
    ]
