# Generated by Django 6.0.2 on 2026-03-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_presences_horaires_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaireemploye',
            name='heure_debut',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='horaireemploye',
            name='heure_fin',
            field=models.TimeField(default='19:00'),
        ),
    ]
