# Generated by Django 6.0.2 on 2026-03-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_horaire_defaut_9h_19h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('patron', 'Patron'), ('manager', 'Manager'), ('employe', 'Employé')], max_length=20),
        ),
    ]
