# Generated by Django 6.0.2 on 2026-03-10 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_employe_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='remise_pourcent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
