# Generated by Django 6.0.2 on 2026-03-10 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remise_pourcent_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloturecaisse',
            name='montant_retrait',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
