# Generated by Django 6.0.2 on 2026-03-27 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_forfaitclient_rdv_achat_credit_achat'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartecadeau',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forfaitclient',
            name='prix_total',
            field=models.IntegerField(help_text='Prix total du forfait après remise éventuelle', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
