# Generated by Django 6.0.2 on 2026-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_cartecadeau_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='forfaitclient',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp réel de création (pour le filtrage clôture)', null=True),
        ),
        migrations.AlterField(
            model_name='paiementcredit',
            name='mode',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('cheque', 'Chèque'), ('om', 'Orange Money'), ('wave', 'Wave'), ('carte_cadeau', 'Carte cadeau'), ('offert', 'Offert')], max_length=20),
        ),
    ]
